use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct CommandInfo {
    pub(crate) name: &'static str,
    pub(crate) summary: &'static str,
    pub(crate) status: &'static str,
    pub(crate) read_only: bool,
    pub(crate) examples: &'static [&'static str],
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ExampleInfo {
    pub(crate) command: &'static str,
    pub(crate) summary: &'static str,
    pub(crate) example: &'static str,
}

pub(crate) const COMMANDS: &[CommandInfo] = &[
    CommandInfo {
        name: "state",
        summary: "Runtime-only presentation state envelope (spirectl.state/v0); state actions returns the native semantic action list.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 state",
            "sts2 --json state",
            "sts2 --json state actions",
            "sts2 --json state --watch --max-events 1",
            "sts2 --json state --perspective omniscient --player-id p2",
        ],
    },
    CommandInfo {
        name: "state watch",
        summary: "Read-only NDJSON stream over the state envelope; uses reactive live bridge watch when available and polling fallback otherwise.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json state --watch --max-events 1",
            "sts2 --json state --watch --watch-mode poll --timeout-ms 10000 --poll-interval-ms 250 --rpc-timeout-ms 1000",
            "sts2 --json state --watch --fail-fast --max-events 1",
        ],
    },
    CommandInfo {
        name: "act play-card",
        summary: "Semantic card play routed through the bridge contract.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 act play-card --card c_17 --target e_2",
            "sts2 act play-card --card c_17 --target e_2 --player-id p2",
        ],
    },
    CommandInfo {
        name: "act use-potion",
        summary: "Use an executable combat potion by stable potion id, with an optional target id when required.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act use-potion --potion potion:p:100:0:fire-potion --target e_1"],
    },
    CommandInfo {
        name: "act choose",
        summary: "Fallback-only compatibility choice execution for generic, modded, or unmodeled visible choices when no modeled intent action exists.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 act choose --choice reward:p1:0",
            "sts2 act choose --choice reward:p2:0 --player-id p2",
            "sts2 act choose --choice event-room:fake-merchant:open-shop",
            "sts2 act choose --choice shop:close-inventory",
            "sts2 act choose --choice map:back",
            "sts2 act choose --choice crystal-sphere:tool:big",
            "sts2 act choose --choice crystal-sphere:cell:0:0",
        ],
    },
    CommandInfo {
        name: "act confirm-selection",
        summary: "Confirm the currently staged selection on a supported selection overlay.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act confirm-selection"],
    },
    CommandInfo {
        name: "act cancel-selection",
        summary: "Cancel the currently staged selection on a supported selection overlay.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act cancel-selection"],
    },
    CommandInfo {
        name: "act mouse click",
        summary: "Dangerous raw viewport mouse click fallback routed through the bridge contract.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --mode dangerous act mouse click --x 100 --y 200"],
    },
    CommandInfo {
        name: "act select-map-node",
        summary: "Select an executable map node by stable node id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act select-map-node --node map-node:3:1"],
    },
    CommandInfo {
        name: "act end-turn",
        summary: "Semantic end-turn execution routed through the bridge contract.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act end-turn", "sts2 act end-turn --player-id p2"],
    },
    CommandInfo {
        name: "act ready",
        summary: "Mark the local multiplayer lobby player ready when the live lobby allows it.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act ready"],
    },
    CommandInfo {
        name: "act unready",
        summary: "Clear the local multiplayer lobby ready state when the live lobby allows it.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act unready"],
    },
    CommandInfo {
        name: "act select-character",
        summary: "Select an executable multiplayer lobby character by stable character id in start-run or load-run lobbies.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 act select-character --character silent",
            "sts2 act select-character --character silent --player-id p:200",
        ],
    },
    CommandInfo {
        name: "act claim-reward",
        summary: "Claim a visible reward by stable reward id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act claim-reward --reward reward:p1:0"],
    },
    CommandInfo {
        name: "act skip-rewards",
        summary: "Skip a visible rewards flow when legal.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act skip-rewards"],
    },
    CommandInfo {
        name: "act select-card",
        summary: "Select a visible card in a supported card-selection flow.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act select-card --card card-selection:card:bash:0"],
    },
    CommandInfo {
        name: "act skip-card-selection",
        summary: "Skip a skippable card-selection flow.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act skip-card-selection"],
    },
    CommandInfo {
        name: "act select-bundle",
        summary: "Select a visible bundle by stable bundle id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act select-bundle --bundle card-selection:bundle:offensive-pack:0"],
    },
    CommandInfo {
        name: "act buy-card",
        summary: "Buy a visible shop card by stable shop item id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act buy-card --shop-item shop:p1:card:strike:0"],
    },
    CommandInfo {
        name: "act buy-relic",
        summary: "Buy a visible shop relic by stable shop item id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act buy-relic --shop-item shop:p1:relic:anchor:0"],
    },
    CommandInfo {
        name: "act buy-potion",
        summary: "Buy a visible shop potion by stable shop item id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act buy-potion --shop-item shop:p1:potion:fire-potion:0"],
    },
    CommandInfo {
        name: "act remove-card",
        summary: "Use a visible shop card-removal service by stable shop item id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act remove-card --shop-item shop:p1:card-removal:0"],
    },
    CommandInfo {
        name: "act leave-shop",
        summary: "Leave a visible shop when legal.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act leave-shop"],
    },
    CommandInfo {
        name: "act close-shop-inventory",
        summary: "Close a visible Fake Merchant shop inventory.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act close-shop-inventory"],
    },
    CommandInfo {
        name: "act rest",
        summary: "Use the visible rest option at a rest site.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act rest"],
    },
    CommandInfo {
        name: "act smith",
        summary: "Use the visible smith option at a rest site.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act smith --card c_1"],
    },
    CommandInfo {
        name: "act use-rest-site-option",
        summary: "Use another visible rest-site option by stable option id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act use-rest-site-option --rest-option heal"],
    },
    CommandInfo {
        name: "act proceed-rest-site",
        summary: "Proceed from a rest site when visible.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act proceed-rest-site"],
    },
    CommandInfo {
        name: "act open-chest",
        summary: "Open a visible treasure-room chest.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act open-chest"],
    },
    CommandInfo {
        name: "act take-relic",
        summary: "Take a visible relic by stable relic id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act take-relic --relic anchor"],
    },
    CommandInfo {
        name: "act proceed-treasure-room",
        summary: "Proceed from a treasure room when visible.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act proceed-treasure-room"],
    },
    CommandInfo {
        name: "act back-from-map",
        summary: "Go back from the map when visible.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act back-from-map"],
    },
    CommandInfo {
        name: "act select-event-option",
        summary: "Select a visible first-party event option by stable option id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act select-event-option --event-option event-room:gain-gold:0"],
    },
    CommandInfo {
        name: "act open-event-shop",
        summary: "Open a visible event shop entry point such as Fake Merchant.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act open-event-shop --event-option event-room:fake-merchant:open-shop"],
    },
    CommandInfo {
        name: "act use-crystal-sphere-control",
        summary: "Use a visible Crystal Sphere control by stable control id.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 act use-crystal-sphere-control --control crystal-sphere:tool:big",
            "sts2 act use-crystal-sphere-control --control crystal-sphere:cell:5:5 --selected-tool small",
        ],
    },
    CommandInfo {
        name: "act proceed-event",
        summary: "Proceed from an event when visible.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act proceed-event"],
    },
    CommandInfo {
        name: "act toggle-map",
        summary: "Toggle the run top-bar map.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act toggle-map"],
    },
    CommandInfo {
        name: "act toggle-deck",
        summary: "Toggle the run top-bar deck view.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act toggle-deck"],
    },
    CommandInfo {
        name: "act inspect-relic",
        summary: "Open the relic-details overlay for a relic-bar relic.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act inspect-relic --relic relic:p:1:0:BURNING_BLOOD"],
    },
    CommandInfo {
        name: "act close-inspect-relic",
        summary: "Close the open relic-details overlay.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act close-inspect-relic"],
    },
    CommandInfo {
        name: "act select-hand-card",
        summary: "Stage a hand card while in-hand selection mode is active (state.run.view.handSelection).",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act select-hand-card --card 12"],
    },
    CommandInfo {
        name: "act deselect-hand-card",
        summary: "Unstage a previously selected hand card from the active in-hand selection.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act deselect-hand-card --card 12"],
    },
    CommandInfo {
        name: "act confirm-hand-selection",
        summary: "Confirm the staged in-hand selection; resolves the awaiting card effect (e.g. Survivor's discard).",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act confirm-hand-selection"],
    },
    CommandInfo {
        name: "act toggle-settings",
        summary: "Toggle the run top-bar settings menu.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act toggle-settings"],
    },
    CommandInfo {
        name: "act sort-deck-view",
        summary: "Sort the current run deck view.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act sort-deck-view --by type"],
    },
    CommandInfo {
        name: "act toggle-deck-view-upgrades",
        summary: "Toggle deck view upgrade previews.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 act toggle-deck-view-upgrades"],
    },
    CommandInfo {
        name: "dev logs",
        summary: "Read recent structured bridge logs, tail a recent window, or follow new entries through the typed transport client.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev logs",
            "sts2 --json dev logs --limit 20 --level warn --target bridge.action",
            "sts2 --json dev logs --after-cursor 120",
            "sts2 dev logs --follow --tail 20",
        ],
    },
    CommandInfo {
        name: "dev console",
        summary: "Execute an explicit mode-gated STS2 in-game developer console command through the live bridge.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev console help",
            "sts2 --json dev console draw 3",
            "sts2 --json dev console help draw",
            "sts2 --json dev console die",
            "sts2 --mode dangerous --json dev console achievement",
            "sts2 --mode dangerous --json dev console cloud",
            "sts2 --mode dangerous --json dev console unlock",
        ],
    },
    CommandInfo {
        name: "dev heal",
        summary: "Instantly heal (or revive) any creature host-side through the game's heal command — a devtool rescue, not a legal player action. Host-direct mutation can desync real remote network clients; fine for couch co-op's single real player.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev heal --amount 10",
            "sts2 --json dev heal --target creature:2 --amount 5",
            "sts2 --json dev heal --full",
        ],
    },
    CommandInfo {
        name: "dev log-health",
        summary: "Fail when the recent runtime log window contains unhealthy error or exception-shaped entries after optional exclusions.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev log-health --tail 100",
            "sts2 --json dev log-health --tail 100 --exclude-target bridge.exception",
            "sts2 --json dev log-health --tail 100 --exclude-message-regex '(?i)known flaky warning'",
        ],
    },
    CommandInfo {
        name: "dev diagnostics",
        summary: "Collect one stable runtime diagnostics payload and optionally write a predictable evidence bundle.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev diagnostics",
            "sts2 --json dev diagnostics --bundle-dir ./.sts2/artifacts/evidence",
            "sts2 --json dev diagnostics --tail 100 --exclude-target bridge.exception",
        ],
    },
    CommandInfo {
        name: "dev mod-reload",
        summary: "Build and request reload for an M57/M60 shell-supported hot-reload project through the live bridge.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev mod-reload --project ./mods/MyHotMod --build --wait",
            "sts2 --json dev mod-reload --project . --wait",
        ],
    },
    CommandInfo {
        name: "dev mod-reload status",
        summary: "Report active shell protocol, generation, last reload report, and restart-required state for a hot-reload project.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev mod-reload status --project ./mods/MyHotMod",
            "sts2 --json dev mod-reload status --project .",
        ],
    },
    CommandInfo {
        name: "dev http",
        summary: "Run one bounded HTTP probe with optional status, header, and JSON/text query assertions.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev http --url http://127.0.0.1:3000/health --expect-status 200",
            "sts2 --json dev http --url http://127.0.0.1:3000/health --query json.status --equals ok",
        ],
    },
    CommandInfo {
        name: "dev http-wait",
        summary: "Poll one HTTP endpoint until the requested status, header, or JSON/text query assertions match.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev http-wait --url http://127.0.0.1:3000/health --expect-status 200 --timeout-ms 10000",
            "sts2 --json dev http-wait --url http://127.0.0.1:3000/health --query json.status --equals ok --interval-ms 250",
        ],
    },
    CommandInfo {
        name: "dev fetch",
        summary: "Fetch one local or HTTP artifact, optionally write it to disk, and assert over parsed JSON/text content.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev fetch --source ./fixtures/health.json",
            "sts2 --json dev fetch --source http://127.0.0.1:3000/build.json --output ./.sts2/artifacts/build.json --query json.status --equals ok",
        ],
    },
    CommandInfo {
        name: "dev websocket",
        summary: "Open one bounded websocket validation session with optional text sends and expected text frames.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev websocket --url ws://127.0.0.1:3001/events --expect-text ready",
            "sts2 --json dev websocket --url ws://127.0.0.1:3001/events --send-text ping --expect-text pong",
        ],
    },
    CommandInfo {
        name: "dev wait-for",
        summary: "Poll bridge-backed state until a simple path assertion succeeds. `--source actions` polls the resolved `state actions` document instead of the plain state snapshot.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev wait-for run.currentRoom.scene --equals rooms/combat_room",
            "sts2 --json dev wait-for run.players[combat.energy>=3].id --timeout-ms 5000 --exists",
            "sts2 --json dev wait-for run.currentRoom.combat.combatState.enemies[*].id --equals e_1 --timeout-ms 5000",
            "sts2 --json dev wait-for actions[kind=select-event-option].id --source actions --exists --timeout-ms 5000",
            "sts2 --json dev wait-for actions[args.eventOptionId=event-room:gain-gold:0].kind --source actions --equals select-event-option --timeout-ms 5000",
        ],
    },
    CommandInfo {
        name: "dev wait-for-transitions",
        summary: "Poll live runtime transition diagnostics until finite transitions and animations settle.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev wait-for-transitions",
            "sts2 --json dev wait-for-transitions --timeout-ms 5000 --interval-ms 50 --stable-samples 3",
        ],
    },
    CommandInfo {
        name: "dev assert",
        summary: "Assert a simple path against the current bridge-backed state. `--source actions` queries the resolved `state actions` document (`spirectl.state-actions/v0`) instead of the plain state snapshot.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev assert run.currentRoom.scene --equals rooms/combat_room",
            "sts2 --json dev assert run.players[id=p1].combat.energy --gte 1",
            "sts2 --json dev assert run.currentRoom.combat.combatState.enemies[*].id --equals e_1",
            "sts2 --json dev assert actions[label*=Turn].id --source actions --equals action:combat-room:end-turn",
            "sts2 --json dev assert actions[args.eventOptionId=event-room:gain-gold:0].kind --source actions --equals select-event-option",
            "sts2 --json dev assert actions[=action:combat-room:end-turn].kind --source actions --equals end-turn",
        ],
    },
    CommandInfo {
        name: "dev fixture record",
        summary: "Record the current screen-entry fixture recipe into ignored local .sts2/fixtures/current-screen storage without claiming exact mid-screen replay.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 dev fixture record"],
    },
    CommandInfo {
        name: "dev fixture resume",
        summary: "Resume the ignored local recorded screen-entry fixture through recipe-backed fixture loading, optionally restarting first.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev fixture resume",
            "sts2 dev fixture resume --restart",
        ],
    },
    CommandInfo {
        name: "dev fixture status",
        summary: "Show whether an ignored local recorded screen fixture exists and what screen it targets.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 dev fixture status"],
    },
    CommandInfo {
        name: "dev fixture clear",
        summary: "Clear the ignored local recorded screen fixture.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 dev fixture clear"],
    },
    CommandInfo {
        name: "dev fixture load",
        summary: "Load an authored sparse recipe fixture into the attached live bridge and report recipeReport/bridgeValidation diagnostics.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev fixture load fixtures/basic-combat.sts2.fixture.yaml",
            "sts2 dev fixture load fixtures/basic-shop-inventory.sts2.fixture.yaml",
            "sts2 dev fixture load fixtures/basic-load-run-lobby.sts2.fixture.yaml",
            "sts2 --json dev fixture load --path fixtures/multiplayer-ownership-local-only-degraded.sts2.fixture.yaml",
        ],
    },
    CommandInfo {
        name: "dev fixture load-latest",
        summary: "Reload the fixture last loaded in this worktree (recorded under .sts2/fixtures/last-loaded.json), optionally restarting first; designed for per-worktree foreach replays.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev fixture load-latest",
            "sts2 dev fixture load-latest --restart",
        ],
    },
    CommandInfo {
        name: "dev scenario export",
        summary: "Export the attached state as a shareable sparse spirectl.scenario/v0 YAML artifact with field-level restoreSupport and optional exact sidecar metadata.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev scenario export --output ./scenarios/combat.sts2.scenario.yaml",
            "sts2 dev scenario export --output ./scenarios/combat.sts2.scenario.yaml --include-exact",
        ],
    },
    CommandInfo {
        name: "dev scenario load",
        summary: "Load a shareable spirectl.scenario/v0 YAML artifact through the live bridge, with field-level restore validation and degraded multiplayer reporting.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev scenario load ./scenarios/combat.sts2.scenario.yaml",
            "sts2 dev scenario load ./scenarios/combat.sts2.scenario.yaml --restart",
            "sts2 dev scenario load --path ./scenarios/combat.sts2.scenario.yaml --allow-degraded-local-multiplayer",
        ],
    },
    CommandInfo {
        name: "dev debug status",
        summary: "Inspect explicit dev-only debug status, leased-session ownership, breakpoint registry, and hook support.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev debug status",
            "sts2 --json dev debug status --session dbg:1",
        ],
    },
    CommandInfo {
        name: "dev debug session start",
        summary: "Start an explicit debugger session as the controller lease owner or as a passive observer.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev debug session start --name smoke-investigation --pause",
            "sts2 --json dev debug session start --role observer --name transcript-watcher",
        ],
    },
    CommandInfo {
        name: "dev debug session status",
        summary: "Inspect one leased debugger session by stable id.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 --json dev debug session status --id dbg:1"],
    },
    CommandInfo {
        name: "dev debug session end",
        summary: "Release a leased debugger session and optionally resume the runtime.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev debug session end --id dbg:1 --resume"],
    },
    CommandInfo {
        name: "dev debug pause",
        summary: "Request a manual pause through the bridge-owned debug control surface.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev debug pause --session dbg:1"],
    },
    CommandInfo {
        name: "dev debug resume",
        summary: "Request a resume through the bridge-owned debug control surface.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev debug resume --session dbg:1"],
    },
    CommandInfo {
        name: "dev debug step",
        summary: "Request a bounded frame/action step through the explicit debug surface.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev debug step --session dbg:1 --kind action --count 1"],
    },
    CommandInfo {
        name: "dev debug events",
        summary: "Replay bounded debugger events by sequence cursor, with optional bounded follow polling.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json dev debug events --session dbg:1 --from-sequence 42 --limit 50",
            "sts2 --json dev debug events --session dbg:observer --follow --timeout-ms 1000",
        ],
    },
    CommandInfo {
        name: "dev debug wait",
        summary: "Resume under a leased debugger session until a breakpoint hits or a timeout elapses.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev debug wait --session dbg:1 --timeout-ms 5000"],
    },
    CommandInfo {
        name: "dev breakpoint list",
        summary: "List registered debug breakpoints and the current live debug status.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 --json dev breakpoint list --session dbg:1"],
    },
    CommandInfo {
        name: "dev breakpoint add",
        summary: "Register a live debug breakpoint with match/change kinds and the shared predicate grammar.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev breakpoint add --path screen.id --equals '\"main-menu\"' --name menu-break",
            "sts2 --json dev breakpoint add --session dbg:1 --path combat.players[0].energy --kind change --min-hit-count 2 --auto-remove-on-hit",
        ],
    },
    CommandInfo {
        name: "dev breakpoint remove",
        summary: "Remove a previously registered debug breakpoint by stable id.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 --json dev breakpoint remove --session dbg:1 --id bp:1"],
    },
    CommandInfo {
        name: "dev screenshot",
        summary: "Capture a bridge-backed PNG screenshot to a file.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev screenshot --output ./.sts2/artifacts/combat.png",
            "sts2 dev screenshot --width 1280 --height 720 --output ./.sts2/artifacts/combat-720p.png",
            "sts2 dev screenshot --preset desktop-1080p --rpc-timeout-ms 5000 --output ./.sts2/artifacts/combat-1080p.png",
        ],
    },
    CommandInfo {
        name: "dev screenshot-diff",
        summary: "Compare a baseline PNG against either a live screenshot or an explicit actual PNG and optionally write a diff bundle.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev screenshot-diff --baseline ./baselines/main-menu.png",
            "sts2 --json dev screenshot-diff --baseline ./baselines/main-menu.png --width 1280 --height 720 --rpc-timeout-ms 5000 --bundle-dir ./.sts2/artifacts/visual/main-menu-720p",
            "sts2 --json dev screenshot-diff --baseline ./baselines/main-menu.png --preset desktop-1080p --bundle-dir ./.sts2/artifacts/visual/main-menu",
            "sts2 --json dev screenshot-diff --baseline ./baselines/main-menu.png --actual ./captures/current-main-menu.png",
        ],
    },
    CommandInfo {
        name: "dev snapshot export",
        summary: "Capture one bounded snapshot-regression baseline bundle from the current runtime.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev snapshot export --spec tests/snapshots/main-menu.sts2.snapshot.yaml --output ./.sts2/artifacts/snapshots/main-menu",
        ],
    },
    CommandInfo {
        name: "dev snapshot compare",
        summary: "Compare a bounded snapshot spec against an exported baseline bundle and optionally write current evidence.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev snapshot compare --spec tests/snapshots/main-menu.sts2.snapshot.yaml --baseline tests/snapshots/baselines/main-menu",
            "sts2 --json dev snapshot compare --spec tests/snapshots/main-menu.sts2.snapshot.yaml --baseline tests/snapshots/baselines/main-menu --bundle-dir ./.sts2/artifacts/snapshots/main-menu",
        ],
    },
    CommandInfo {
        name: "dev visual-preflight",
        summary: "Run a bounded live visual preflight report with catalog explain, manifest-ready batch extraction, and artifact validation guidance.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev visual-preflight --encounter kaiser_crab_boss --print-only",
            "sts2 --json dev visual-preflight --encounter ovicopter_normal --print-only",
            "sts2 --json dev visual-preflight --repair-stale-endpoint --attach",
            "sts2 --json dev visual-preflight --launch --timeout-ms 30000 --interval-ms 250",
        ],
    },
    CommandInfo {
        name: "dev scene tree",
        summary: "Inspect the recursive live Godot runtime scene tree under an optional normalized /root path, with optional layout/render properties for calibration.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev scene tree",
            "sts2 --json dev scene tree /root/CombatScreen",
            "sts2 --json dev scene tree /root --properties --computed-transform",
        ],
    },
    CommandInfo {
        name: "dev scene node",
        summary: "Describe one exact live Godot runtime scene node and its direct children by normalized /root path, with opt-in developer properties including text-bearing label diagnostics.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev scene node /root",
            "sts2 --json dev scene node /root/CombatScreen/HandPanel",
            "sts2 --json dev scene node /root/CombatScreen/BgContainer --properties --computed-transform",
            "sts2 --json dev scene node /root/EventRoom/MegaRichTextLabel --properties",
        ],
    },
    CommandInfo {
        name: "dev scene children",
        summary: "Inspect the direct children of one exact live Godot runtime scene node by normalized /root path.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 dev scene children /root/CombatScreen",
            "sts2 --json dev scene children /root/CombatScreen --properties",
        ],
    },
    CommandInfo {
        name: "dev scene hover",
        summary: "Hover one live Godot Control by normalized /root path or current presentation element id and optionally return visible HoverTip text.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev scene hover --path /root/CharacterSelect/DEFECT_button --hover-tip",
            "sts2 --json dev scene hover --element-id character:defect:tile --hover-tip --settle-ms 100",
        ],
    },
    CommandInfo {
        name: "dev scene unhover",
        summary: "Revert a prior dev scene hover: move the pointer to a neutral point to clear any active hover/tooltip and, when a target is given, invoke that live Godot Control's unfocus hook. Target is optional (omit for a global clear).",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json dev scene unhover",
            "sts2 --json dev scene unhover --path /root/CharacterSelect/DEFECT_button",
        ],
    },
    CommandInfo {
        name: "dev scene set-visible",
        summary: "Set transient runtime visibility for one live Godot CanvasItem scene node by normalized /root path, with optional post-mutation stability verification.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 dev scene set-visible /root/Game/RootSceneContainer/Run/GlobalUi/DebugInfo --hidden",
            "sts2 --json dev scene set-visible /root/Game/RootSceneContainer/Run/GlobalUi/DebugInfo --visible --verify-after-ms 300",
        ],
    },
    CommandInfo {
        name: "game detect",
        summary: "Report configured or detected game path status.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 game detect", "sts2 --json game detect"],
    },
    CommandInfo {
        name: "game info",
        summary: "Describe the configured transport and bridge handshake state.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 game info", "sts2 --json game info"],
    },
    CommandInfo {
        name: "game bridge-health",
        summary: "Diagnose live bridge readiness without mutating game files or processes.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 game bridge-health",
            "sts2 --json game bridge-health --rpc-timeout-ms 1000",
            "sts2 --json game bridge-health --verbose",
        ],
    },
    CommandInfo {
        name: "game install-bridge",
        summary: "Build and install only the bridge payload into the configured mods directory.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 game install-bridge",
            "sts2 --json game install-bridge",
        ],
    },
    CommandInfo {
        name: "game launch",
        summary: "Close any existing configured game process, then launch a fresh one.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 game launch",
            "sts2 game launch --timeout-ms 30000 --interval-ms 250",
            "sts2 game launch --verify-stable-ms 2000",
            "sts2 game launch --no-detach-session",
            "sts2 game launch -- --headless -fastmp host_standard",
        ],
    },
    CommandInfo {
        name: "game mods settings",
        summary: "Read enabled and disabled mod ids from the saved STS2 mod settings file.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json game mods settings",
            "sts2 --json game mods settings --settings-file ~/.local/share/SlayTheSpire2/steam/76561198072573591/settings.save",
        ],
    },
    CommandInfo {
        name: "game mods active",
        summary: "List mods reported by the live game through the bridge.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 --json game mods active", "sts2 game mods active"],
    },
    CommandInfo {
        name: "game instances",
        summary: "List or prune named game instances (per-instance bridge socket + Godot user-dir; active instance may come from --instance, SPIRECTL_INSTANCE, or instances.default).",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 game instances",
            "sts2 --json game instances list",
            "sts2 game instances prune",
            "sts2 --instance alpha game launch",
            "sts2 --instance alpha game state",
            "sts2 --instance dev --isolated-build game launch",
            "sts2 game launch",
        ],
    },
    CommandInfo {
        name: "game attach",
        summary: "Poll the configured Unix-socket bridge until live IPC attachment succeeds.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 game attach",
            "sts2 game attach --timeout-ms 30000 --interval-ms 250",
        ],
    },
    CommandInfo {
        name: "game close",
        summary: "Gracefully stop the local game process through bridge, configured stop command, or exact platform process matching.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 game close",
            "sts2 game close --timeout-ms 30000 --interval-ms 250",
            "sts2 --json game close",
        ],
    },
    CommandInfo {
        name: "game kill",
        summary: "Force terminate exact local game process matches.",
        status: "implemented",
        read_only: false,
        examples: &["sts2 game kill", "sts2 --json game kill"],
    },
    CommandInfo {
        name: "game deploy",
        summary: "Deploy the bridge plus a mod project, with optional build, restart, and verify.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 game deploy ./mods/MyMod --build --restart --verify",
            "sts2 game deploy ./mods/MyMod --build --timeout-ms 30000 --interval-ms 250",
            "sts2 game deploy ./mods/MyMod --restart --verify --verify-stable-ms 2000",
        ],
    },
    CommandInfo {
        name: "service serve",
        summary: "Run the CLI-owned HTTP/JSON automation service for remote metadata and bounded automation access.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json service serve",
            "sts2 --json service serve --listen 127.0.0.1:4317 --auth-token local-dev-token",
            "sts2 --json service serve --mcp-mode network --mcp-listen 127.0.0.1:4318 --mcp-auth-token local-mcp-token",
            "sts2 --json service serve --job-store durable",
            "sts2 --json service serve --job-store durable --job-store-dir remote-jobs",
        ],
    },
    CommandInfo {
        name: "config resolve",
        summary: "Resolve config into absolute install paths (gamePath, assembliesDir, resourcesDir, modsDir, instancesDir, artifactsDir) with the source of each value, so scripts never re-parse sts2.local.yaml.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json config resolve",
            "sts2 --json config resolve modsDir",
            "sts2 --json config resolve gamePath assembliesDir",
        ],
    },
    CommandInfo {
        name: "toolchain info",
        summary: "Report managed toolchain roots, config provenance, and offline helper availability.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 toolchain info", "sts2 --json toolchain info"],
    },
    CommandInfo {
        name: "project recover",
        summary: "Own stable repo-local offline recovery outputs and manifests under the managed toolchain root.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 project recover --kind decompile",
            "sts2 --json project recover --kind all",
        ],
    },
    CommandInfo {
        name: "project scaffold stable-harmony-trampoline",
        summary: "Create a downstream stable Harmony trampoline hot-reload project with generated local profiles.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 project scaffold stable-harmony-trampoline --output ./mods/MyHotMod --mod-id my-hot-mod --name \"My Hot Mod\" --namespace MyHotMod",
            "sts2 project scaffold stable-harmony-trampoline --output ./mods/MyHotMod --mod-id my-hot-mod --name \"My Hot Mod\" --namespace MyHotMod --enable-guardrails",
            "sts2 --json project scaffold stable-harmony-trampoline --output ./mods/MyHotMod --mod-id my-hot-mod --name \"My Hot Mod\" --namespace MyHotMod --force-empty",
            "sts2 project profile run my-hot-mod-shell-deploy-restart",
            "sts2 project profile run my-hot-mod-logic-build",
        ],
    },
    CommandInfo {
        name: "project profile list",
        summary: "List checked-in profiles that may compose lifecycle and repo-local command steps.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 project profile list",
            "sts2 --json project profile list",
        ],
    },
    CommandInfo {
        name: "project profile show",
        summary: "Show one resolved checked-in profile with lifecycle and repo-local command steps.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 project profile show install-launch-and-attach",
            "sts2 --json project profile show install-launch-and-attach",
        ],
    },
    CommandInfo {
        name: "project profile run",
        summary: "Run one checked-in profile by composing lifecycle commands and repo-local command steps.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 project profile run install-bridge",
            "sts2 --json project profile run install-launch-and-attach",
        ],
    },
    CommandInfo {
        name: "project hook list",
        summary: "List registered repo-local validation hooks from the checked-in hooks file.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 project hook list", "sts2 --json project hook list"],
    },
    CommandInfo {
        name: "project hook show",
        summary: "Show one registered repo-local validation hook with resolved command and cwd paths.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 project hook show repo-check",
            "sts2 --json project hook show repo-check",
        ],
    },
    CommandInfo {
        name: "project hook run",
        summary: "Run one registered repo-local validation hook through the JSON stdin/stdout contract.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 project hook run repo-check",
            "sts2 --json project hook run repo-check --input '{\"kind\":\"smoke\"}'",
        ],
    },
    CommandInfo {
        name: "code locate",
        summary: "Locate types and methods in installed game or mod assemblies.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code locate type CombatScreen",
            "sts2 --json code locate method DrawCard --include-mods --include-dependencies",
        ],
    },
    CommandInfo {
        name: "code describe",
        summary: "Describe an exact type or method with structured metadata.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code describe type MegaCrit.Sts2.CardState",
            "sts2 --json code describe method \"MegaCrit.Sts2.CardState::CanPlay()\"",
        ],
    },
    CommandInfo {
        name: "code decompile",
        summary: "Show metadata-derived text by default, or ILSpy-backed output with --full.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code decompile type MegaCrit.Sts2.CardState",
            "sts2 --json code decompile method \"MegaCrit.Sts2.CardState::CanPlay()\" --full",
        ],
    },
    CommandInfo {
        name: "code refs",
        summary: "Find static references to an exact type or method, or do name-based fallback reference search.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code refs type MegaCrit.Sts2.CardState",
            "sts2 --json code refs symbol CanPlay --include-mods --include-dependencies",
        ],
    },
    CommandInfo {
        name: "code derived",
        summary: "Find direct derived classes, implementers, and interface inheritance relationships for a type.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code derived type MegaCrit.Sts2.CardState",
            "sts2 --json code derived type MegaCrit.Sts2.BaseCard",
        ],
    },
    CommandInfo {
        name: "code hooks",
        summary: "List static managed hook candidates with pagination, filters, script hints, and staged follow-up ids.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code hooks --assemblies-dir ./assemblies",
            "sts2 --json code hooks _Ready --assemblies-dir ./assemblies --resources-dir ./game-project --limit 50 --has-script",
        ],
    },
    CommandInfo {
        name: "code hook-info",
        summary: "Resolve one exact managed hook candidate into a hook-ready method signature projection.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code hook-info method:Game:Namespace.Type::Method(System.String) --assemblies-dir ./assemblies",
            "sts2 --json code hook-info \"Namespace.Type::Method(System.String)\" --assemblies-dir ./assemblies",
        ],
    },
    CommandInfo {
        name: "code verify-references",
        summary: "Check whether built consumer assemblies still bind to a game build, reporting missing types, missing members, and reshaped signatures.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code verify-references ./mods/example/Example.dll --assemblies-dir ./assemblies",
            "sts2 --json code verify-references ./mods/example/Example.dll,./mods/example/Example.Bridge.dll --assemblies-dir ./beta-assemblies --control-assemblies-dir ./assemblies",
        ],
    },
    CommandInfo {
        name: "code scene-search",
        summary: "Search static Godot text, binary, and packed scenes, nodes, and resources without using the runtime bridge.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code scene-search HandPanel --resources-dir ./game-project",
            "sts2 --json code scene-search StatusConfig --resources-dir ./game-project --assemblies-dir ./assemblies",
        ],
    },
    CommandInfo {
        name: "code scene-tree",
        summary: "Show one exact static Godot scene tree from supported text, binary, or packed scene assets.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code scene-tree res://ui/CombatScreen.tscn --resources-dir ./game-project",
            "sts2 --json code scene-tree scene:game:res://ui/CombatScreen.tscn --resources-dir ./game-project",
        ],
    },
    CommandInfo {
        name: "code scene-node",
        summary: "Describe one exact static Godot scene node from supported text, binary, or packed scene assets, including NodePath and resource references.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 code scene-node res://ui/shared/HandPanel.tscn /HandPanel/ConfirmButton --resources-dir ./game-project",
            "sts2 --json code scene-node res://ui/shared/HandPanel.tscn /HandPanel --resources-dir ./game-project --assemblies-dir ./assemblies",
        ],
    },
    CommandInfo {
        name: "assets extract",
        summary: "Search filesystem, packed, font, typed model-backed assets, and composed render targets, and export them with offline/live execution modes.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 assets extract hand --resources-dir ./game-project",
            "sts2 --json assets extract title_font --execution offline --resources-dir ./game-project",
            "sts2 --json assets extract packed_icon --execution offline --resources-dir ./game-project",
            "sts2 --json assets extract anim --execution live --format png --resources-dir ./game-project --game-path ~/games/sts2",
            "sts2 --json assets extract model://characters/ironclad/visuals --execution live",
            "sts2 --json assets extract model://characters/ironclad/iconOutline --execution live --format png",
            "sts2 --json assets extract model://characters/ironclad/characterSelectIcon --execution live --format png",
            "sts2 --json assets extract model://relics/burning-blood/bigIcon --execution live --format png",
            "sts2 --json assets extract res://scenes/vfx/block_spark_vfx.tscn --execution live --format png",
            "sts2 --json assets extract composed://combat-background/hive/image --execution live --format png",
            "sts2 --json assets extract composed://encounters/kaiser_crab_boss/background/image --execution live --format png",
            "sts2 --json assets extract composed://encounters/kaiser_crab_boss/visual-state/rocket-charge-up/overlay/image --execution live --format png",
            "sts2 --json assets extract composed://encounters/kaiser_crab_boss/visual-part/rocket/state/rocket-charge-up/image --execution live --format png",
            "sts2 --json assets extract composed://encounters/knowledge_demon_boss/visual-part/burn-fire/state/heavy-attack-burnt/image --execution live --format png",
        ],
    },
    CommandInfo {
        name: "assets catalog",
        summary: "List supported typed semantic asset key families and their model/composed provenance.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json assets catalog --execution live",
            "sts2 --json assets catalog --family model",
            "sts2 --json assets catalog --family model:characters",
        ],
    },
    CommandInfo {
        name: "models",
        summary: "Export immutable live game model metadata for a model family; localized text is returned as loc refs by default, or resolved with --language <code|auto>.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json models characters",
            "sts2 --json models --language esp characters",
            "sts2 --json models --language auto characters",
            "sts2 --json models cards strike-ironclad",
            "sts2 --json models characters ironclad silent",
            "sts2 --json models relics burning-blood",
            "sts2 --json models events room-full-of-cheese",
            "sts2 --json models ancients neow",
            "sts2 --json models acts overgrowth",
            "sts2 --json models monsters jaw-worm",
            "sts2 --json models encounters jaw-worm-weak",
            "sts2 --json models powers strength",
            "sts2 --json models enchantments innate",
        ],
    },
    CommandInfo {
        name: "reference",
        summary: "Export live game reference data that is constant at runtime but is not a game model. Built-in topics: colors (the StsColors palette) and version (game version, date, and modding summary). Topics are server-defined and extensible.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json reference colors",
            "sts2 --json reference colors aqua gold screenBackdrop",
            "sts2 --json reference version",
        ],
    },
    CommandInfo {
        name: "assets resolve",
        summary: "Resolve one typed semantic asset key to its model/composed provider provenance.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json assets resolve model://characters/defect/characterSelectIcon --execution live",
            "sts2 --json assets resolve composed://combat-background/hive/image --execution live",
        ],
    },
    CommandInfo {
        name: "assets explain",
        summary: "Explain composed live asset decisions, expanded encounter package metadata, selector diagnostics, render diagnostics, isolation evidence, bounds, notices, and warnings without writing artifacts.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 --json assets explain composed://combat-background/overgrowth/image --execution live",
            "sts2 --json assets explain composed://encounters/kaiser_crab_boss/scene-package --execution live",
            "sts2 --json assets explain composed://encounters/knowledge_demon_boss/scene-package --execution live",
        ],
    },
    CommandInfo {
        name: "assets extract-batch",
        summary: "Extract many filesystem, packed, or virtual model-backed assets from a generic JSON manifest while preserving per-request combat catalog notes, notices, provenance, failures, render diagnostics, and artifact-check diagnostics.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json assets extract-batch --manifest ./asset-manifest.json --output ./.sts2/artifacts/mock-assets --format png",
            "sts2 --json assets extract-batch --manifest ./asset-manifest.json --execution offline --resources-dir ./game-project",
            "sts2 --json assets extract-batch --manifest ./encounter-asset-manifest.json --output ./.sts2/artifacts/encounters --execution live --format png",
            "scripts/validate.sh m78-live-encounter-artifacts --encounter kaiser_crab_boss --json",
        ],
    },
    CommandInfo {
        name: "skill install",
        summary: "Install the checked-in spirectl skill pack into a project-local .agents/skills directory or an explicit root path.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 skill install",
            "sts2 skill install ./vendor/skills",
            "sts2 --json skill install",
            "sts2 --json skill install --path ./vendor/skills",
        ],
    },
    CommandInfo {
        name: "completion",
        summary: "Generate shell completion text from the authoritative clap command tree.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 completion",
            "sts2 completion bash",
            "sts2 --json completion fish",
        ],
    },
    CommandInfo {
        name: "completion install",
        summary: "Install shell completion text into a spirectl-managed per-user path or an explicit file path and print activation metadata.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 completion install",
            "sts2 completion install zsh",
            "sts2 --json completion install --path ~/.config/spirectl/completions/sts2.bash",
        ],
    },
    CommandInfo {
        name: "inspect commands",
        summary: "List self-describing command metadata.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 inspect commands", "sts2 --json inspect commands"],
    },
    CommandInfo {
        name: "inspect examples",
        summary: "List example invocations from the command catalog.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 inspect examples",
            "sts2 inspect examples --command \"code locate\"",
        ],
    },
    CommandInfo {
        name: "inspect actions",
        summary: "Describe bridge-supported actions and current availability, with explicit --offline/mock paths for static metadata rendering without a live host.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 inspect actions",
            "sts2 --json inspect actions",
            "sts2 --json inspect actions --offline",
            "sts2 --config tests/sts2.mock.yaml --json inspect actions",
        ],
    },
    CommandInfo {
        name: "inspect state-schema",
        summary: "Describe the compact agent-first state schema, legacy migration path, and stable join rules.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 inspect state-schema",
            "sts2 --json inspect state-schema",
        ],
    },
    CommandInfo {
        name: "inspect reference-topics",
        summary: "List checked-in modding discovery and hot-reload workflow references, limits, and staged command sequences.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 inspect reference-topics",
            "sts2 --json inspect reference-topics",
        ],
    },
    CommandInfo {
        name: "inspect viewport-presets",
        summary: "List the effective viewport preset catalog available to visual capture commands.",
        status: "implemented",
        read_only: true,
        examples: &[
            "sts2 inspect viewport-presets",
            "sts2 --json inspect viewport-presets",
            "sts2 --json inspect viewport-presets --preset-catalog ./tests/visual/sample-catalog.sts2.viewport-presets.yaml",
        ],
    },
    CommandInfo {
        name: "inspect ai-tools",
        summary: "Describe the thin AI adapter tool catalog mapped onto the CLI surface.",
        status: "implemented",
        read_only: true,
        examples: &["sts2 inspect ai-tools", "sts2 --json inspect ai-tools"],
    },
    CommandInfo {
        name: "test run",
        summary: "Execute YAML- or JSON-authored test scenarios with persisted summaries and failure artifacts.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --json test run --profile mock",
            "sts2 --json test run --profile live --tag spec:S74",
            "sts2 --config tests/sts2.mock.yaml test run tests/scenarios/smoke-main-menu.sts2.yaml",
            "sts2 --config tests/sts2.mock.yaml --json test run tests/scenarios/smoke-main-menu.sts2.yaml",
            "sts2 --json test run tests/scenarios/smoke-main-menu-live.sts2.yaml",
            "sts2 --json test run ./tmp/smoke-main-menu.sts2.json",
            "sts2 --json test run --inline '{name: smoke-inline, steps: [game.info]}'",
            "sts2 --config tests/sts2.mock.yaml --json test run --artifacts-dir ./tmp/sts2-artifacts tests/scenarios/smoke-main-menu.sts2.yaml",
            "sts2 --config tests/sts2.mock.yaml --json test run --failure-artifacts never tests/scenarios/smoke-main-menu.sts2.yaml",
        ],
    },
    CommandInfo {
        name: "test stress",
        summary: "Repeat an existing scenario path under bounded iteration or duration controls and persist aggregate summaries.",
        status: "implemented",
        read_only: false,
        examples: &[
            "sts2 --config tests/sts2.mock.yaml --json test stress --iterations 10 tests/scenarios/regression-main-menu.sts2.yaml",
            "sts2 --config tests/sts2.mock.yaml --json test stress --duration-ms 60000 --max-failures 2 --cooldown-ms 500 tests/scenarios/regression-main-menu.sts2.yaml",
        ],
    },
];

pub(crate) fn catalog_examples(command_filter: Option<&str>) -> Vec<ExampleInfo> {
    COMMANDS
        .iter()
        .filter(|command| {
            command_filter
                .map(|filter| command.name == filter)
                .unwrap_or(true)
        })
        .flat_map(|command| {
            command.examples.iter().map(move |example| ExampleInfo {
                command: command.name,
                summary: command.summary,
                example,
            })
        })
        .collect()
}

pub(crate) fn command_info(name: &str) -> &'static CommandInfo {
    COMMANDS
        .iter()
        .find(|command| command.name == name)
        .expect("command catalog entry")
}
