using Spirectl.Sts2.Core.Protocol;

namespace Spirectl.Sts2.Core.State;

public sealed record BridgeRuntimeObservation(
    string SchemaVersion,
    string GameVersion,
    string BridgeVersion,
    DataSourceKind Source,
    bool Provisional,
    string ScreenType,
    string ScreenTitle,
    string ScreenInstanceId,
    string? DefaultPlayerId,
    MenuStateSnapshot? Menu,
    LobbyStateSnapshot? Lobby,
    RunStateSnapshot? Run,
    CombatStateSnapshot? Combat,
    MapStateSnapshot? Map,
    EventRoomStateSnapshot? EventRoom,
    TreasureRoomStateSnapshot? TreasureRoom,
    RelicSelectionStateSnapshot? RelicSelection,
    RestSiteStateSnapshot? RestSite,
    ShopStateSnapshot? Shop,
    RewardsStateSnapshot? Rewards,
    CardSelectionStateSnapshot? CardSelection,
    SimpleCardSelectionStateSnapshot? SimpleCardSelection,
    DeckCardSelectionStateSnapshot? DeckCardSelection,
    BundleSelectionStateSnapshot? BundleSelection,
    MultiplayerLobbyStateSnapshot? MultiplayerLobby,
    IReadOnlyList<ChoiceSnapshot> Choices,
    IReadOnlyList<AvailableActionSnapshot> AvailableActions,
    IReadOnlyList<StateNoticeSnapshot> Notices,
    DebugStateSnapshot? Debug,
    string? ScreenSource = null,
    string? ScreenRawType = null,
    string? ScreenClassName = null,
    CardOverlayStateSnapshot? CardOverlay = null,
    string? Language = null)
{
    public BridgeRuntimeObservation(
        string SchemaVersion,
        string GameVersion,
        string BridgeVersion,
        DataSourceKind Source,
        bool Provisional,
        string ScreenType,
        string ScreenTitle,
        string ScreenInstanceId,
        string? DefaultPlayerId,
        MenuStateSnapshot? Menu,
        LobbyStateSnapshot? Lobby,
        RunStateSnapshot? Run,
        CombatStateSnapshot? Combat,
        IReadOnlyList<ChoiceSnapshot> Choices,
        IReadOnlyList<AvailableActionSnapshot> AvailableActions,
        IReadOnlyList<StateNoticeSnapshot> Notices,
        DebugStateSnapshot? Debug,
        string? ScreenSource = null,
        string? ScreenRawType = null,
        string? ScreenClassName = null,
        string? Language = null)
        : this(
            SchemaVersion,
            GameVersion,
            BridgeVersion,
            Source,
            Provisional,
            ScreenType,
            ScreenTitle,
            ScreenInstanceId,
            DefaultPlayerId,
            Menu,
            Lobby,
            Run,
            Combat,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            Choices,
            AvailableActions,
            Notices,
            Debug,
            ScreenSource,
            ScreenRawType,
            ScreenClassName,
            null,
            Language)
    {
    }
}
