using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HotMod.Guardrails;

[Generator]
public sealed class HotPatchGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
    namespace HotMod.Shell.Guardrails;

    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class HotPatchAttribute : System.Attribute
    {
        public string TargetType { get; init; } = "";
        public string TargetMethod { get; init; } = "";
        public HotPatchHook Hook { get; init; } = HotPatchHook.Postfix;
        public string Dispatch { get; init; } = "";
    }

    internal enum HotPatchHook
    {
        Prefix,
        Postfix
    }
    """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var shellAssembly = context.CompilationProvider.Select(static (compilation, _) =>
            (compilation.AssemblyName ?? "").EndsWith(".Shell", StringComparison.Ordinal));
        context.RegisterSourceOutput(shellAssembly, static (sourceContext, isShellAssembly) =>
        {
            if (isShellAssembly)
            {
                sourceContext.AddSource("HotPatchAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            }
        });

        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntaxContext, _) => HotPatchDeclaration.From(syntaxContext))
            .Where(static declaration => declaration is not null);

        context.RegisterSourceOutput(
            declarations.Combine(shellAssembly),
            static (sourceContext, pair) =>
            {
                var declaration = pair.Left!;
                var isShellAssembly = pair.Right;
                if (!isShellAssembly)
                {
                    return;
                }

                if (declaration.HasMissingRequiredValue)
                {
                    sourceContext.ReportDiagnostic(Diagnostic.Create(
                        GuardrailDiagnostics.InvalidHotPatchDeclaration,
                        declaration.Location,
                        declaration.ClassName));
                    return;
                }

                sourceContext.AddSource(declaration.HintName, SourceText.From(Render(declaration), Encoding.UTF8));
            });
    }

    private static string Render(HotPatchDeclaration declaration)
    {
        var hookMethod = declaration.Hook == "Prefix" ? "Prefix" : "Postfix";
        return $$"""
        // <auto-generated />
        using System.Collections.Generic;
        using HotMod.Shell.Runtime;

        namespace {{declaration.Namespace}};

        #if HOTMOD_STS2
        [global::HarmonyLib.HarmonyPatch]
        #endif
        {{declaration.Accessibility}} sealed partial class {{declaration.ClassName}}
        {
        #if HOTMOD_STS2
            private static System.Reflection.MethodBase? TargetMethod()
            {
                return global::HarmonyLib.AccessTools.Method("{{Escape(declaration.TargetType)}}:{{Escape(declaration.TargetMethod)}}");
            }

            private static void {{hookMethod}}()
            {
                DispatchForTest();
            }
        #endif

            public static void DispatchForTest(IReadOnlyDictionary<string, string>? values = null)
            {
                HotRuntime.Current.DispatchHook("{{Escape(declaration.Dispatch)}}", values ?? new Dictionary<string, string>());
            }
        }
        """;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class HotPatchDeclaration
    {
        private HotPatchDeclaration(
            string ns,
            string accessibility,
            string className,
            string targetType,
            string targetMethod,
            string hook,
            string dispatch,
            Location? location)
        {
            Namespace = ns;
            Accessibility = accessibility;
            ClassName = className;
            TargetType = targetType;
            TargetMethod = targetMethod;
            Hook = hook;
            Dispatch = dispatch;
            Location = location;
        }

        public string Namespace { get; }

        public string Accessibility { get; }

        public string ClassName { get; }

        public string TargetType { get; }

        public string TargetMethod { get; }

        public string Hook { get; }

        public string Dispatch { get; }

        public Location? Location { get; }

        public string HintName => $"HotReloadPatch_{Sanitize(Namespace)}_{Sanitize(ClassName)}.g.cs";

        public bool HasMissingRequiredValue =>
            string.IsNullOrWhiteSpace(TargetType)
            || string.IsNullOrWhiteSpace(TargetMethod)
            || string.IsNullOrWhiteSpace(Dispatch);

        public static HotPatchDeclaration? From(GeneratorSyntaxContext context)
        {
            var declaration = (ClassDeclarationSyntax)context.Node;
            var attribute = declaration.AttributeLists
                .SelectMany(list => list.Attributes)
                .FirstOrDefault(IsHotPatchAttribute);
            if (attribute is null)
            {
                return null;
            }

            var type = context.SemanticModel.GetDeclaredSymbol(declaration);
            if (type is null)
            {
                return null;
            }

            return new HotPatchDeclaration(
                type.ContainingNamespace.ToDisplayString(),
                type.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public ? "public" : "internal",
                type.Name,
                Value(context.SemanticModel, attribute, "TargetType"),
                Value(context.SemanticModel, attribute, "TargetMethod"),
                HookName(attribute),
                Value(context.SemanticModel, attribute, "Dispatch"),
                type.Locations.FirstOrDefault());
        }

        private static bool IsHotPatchAttribute(AttributeSyntax attribute)
        {
            var name = attribute.Name.ToString();
            return name == "HotPatch"
                || name == "HotPatchAttribute"
                || name.EndsWith(".HotPatch", StringComparison.Ordinal)
                || name.EndsWith(".HotPatchAttribute", StringComparison.Ordinal);
        }

        private static string Value(SemanticModel semanticModel, AttributeSyntax attribute, string name)
        {
            foreach (var argument in attribute.ArgumentList?.Arguments ?? default(SeparatedSyntaxList<AttributeArgumentSyntax>))
            {
                if (argument.NameEquals?.Name.Identifier.ValueText == name)
                {
                    return semanticModel.GetConstantValue(argument.Expression).Value?.ToString() ?? "";
                }
            }

            return "";
        }

        private static string HookName(AttributeSyntax attribute)
        {
            foreach (var argument in attribute.ArgumentList?.Arguments ?? default(SeparatedSyntaxList<AttributeArgumentSyntax>))
            {
                if (argument.NameEquals?.Name.Identifier.ValueText == "Hook")
                {
                    return argument.Expression.ToString().EndsWith(".Prefix", StringComparison.Ordinal)
                        || argument.Expression.ToString() == "Prefix"
                        || argument.Expression.ToString() == "HotPatchHook.Prefix"
                        ? "Prefix"
                        : "Postfix";
                }
            }

            return "Postfix";
        }

        private static string Sanitize(string value)
        {
            var builder = new StringBuilder(value.Length);
            foreach (var ch in value)
            {
                builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            }

            return builder.ToString();
        }
    }
}
