/**
 * Pure Spine clip and geoclip sources for renderers that own their own canvas, WebGL, and resource loading.
 * This module intentionally has no DOM, fetch, image decoding, or mounted-surface dependency.
 */
export type { SpineDiagnostic, SpineResult } from "./diagnostics";
export {
  parseRasterSpineClip,
  rasterSpineFrameIndexAt,
  createRasterSpineFrameSampleScratch,
  sampleRasterSpineClip,
  sampleRasterSpineClipInto,
  type RasterSpineClip,
  type RasterSpineFrame,
  type RasterSpineFrameSample,
  type RasterSpineFrameSampleScratch,
  type SpinePlacement,
} from "./rasterClip";
export {
  applyGeoclipVerts,
  applyGeoclipTransform,
  applyGeoclipTransformInto,
  createGeoclipFrameSampleScratch,
  foldGeoclipUvs,
  geoclipFrameIndexAt,
  parseGeoclip,
  recoverGeoclip,
  recoverGeoclipVerts,
  recoveringGeoclipFrameIndexAt,
  refoldGeoclipTextureDimensions,
  sampleGeoclip,
  sampleGeoclipInto,
  sampleRecoveringGeoclipFrame,
  validateGeoclipTextureDimensions,
  type Geoclip,
  type GeoclipRecoveryReport,
  type RecoveringGeoclip,
  type RecoveringGeoclipFrame,
  type RecoveringGeoclipPage,
  type RecoveringGeoclipPart,
  type RecoveringGeoclipPlacement,
  type RecoveringGeoclipSlot,
  type RecoveringGeoclipVertexBin,
  type RecoveringGeoclipMesh,
  type RecoveringGeoclipFrameSample,
  type GeoclipFrameSample,
  GeoclipFrameSampleScratch,
  type GeoclipMesh,
  type GeoclipMeshScratch,
  type GeoclipPage,
  type GeoclipPart,
  type GeoclipPlacement,
  type GeoclipVertexBin,
  type GeoclipTextureDimensions,
  type GeoclipTextureDimensionsResolver,
  type SpineTextureSource,
  type SpineTextureSourceResolver,
} from "./geoclip";
