namespace Spirectl.DotnetTools.Models;

public sealed record InspectionMatch(
    string Id,
    string Kind,
    string DisplayName,
    string FullName,
    string? Namespace,
    string? Assembly,
    string? AssemblyPath,
    string Source,
    string MatchKind,
    int Score,
    string? Signature,
    string? SceneId = null,
    string? ScenePath = null,
    string? SceneUid = null,
    string? StorageKind = null,
    string? ContainerPath = null,
    string? ResourcePath = null,
    string? ResourceType = null,
    string? NodePath = null,
    string? AttachedScriptPath = null,
    string? AttachedScriptType = null,
    string? AttachedScriptTypeId = null,
    IReadOnlyList<string>? HookForms = null,
    IReadOnlyList<string>? Reasons = null,
    string? ScriptPath = null,
    IReadOnlyList<string>? ScenePaths = null,
    IReadOnlyList<string>? SuggestedNextCommands = null,
    string? DeclaringType = null,
    string? DeclaringTypeId = null,
    string? Visibility = null,
    bool? IsStatic = null,
    bool? IsAbstract = null,
    bool? IsVirtual = null,
    int? ReferenceCount = null);
